"""Init

Revision ID: 31a56be8c234
Revises:
Create Date: 2025-05-16 20:45:36.310165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31a56be8c234"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_registration",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_app_registration_tg_id"),
        "app_registration",
        ["tg_id"],
        unique=False,
    )
    op.create_table(
        "app_search_attempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("number", sa.String(), nullable=False),
        sa.Column(
            "date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_app_search_attempt_tg_id"),
        "app_search_attempt",
        ["tg_id"],
        unique=False,
    )
    op.create_table(
        "app_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_app_user_tg_id"), "app_user", ["tg_id"], unique=True
    )
    op.create_table(
        "app_auto",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_app_auto_number"), "app_auto", ["number"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_app_auto_number"), table_name="app_auto")
    op.drop_table("app_auto")
    op.drop_index(op.f("ix_app_user_tg_id"), table_name="app_user")
    op.drop_table("app_user")
    op.drop_index(
        op.f("ix_app_search_attempt_tg_id"), table_name="app_search_attempt"
    )
    op.drop_table("app_search_attempt")
    op.drop_index(
        op.f("ix_app_registration_tg_id"), table_name="app_registration"
    )
    op.drop_table("app_registration")
    # ### end Alembic commands ###
