volumes:
  dev_bot_car_number_pg_data:

services:
  db:
    container_name: dev_bot_car_number_db
    image: postgres
    env_file: ../.env
    volumes:
      - dev_bot_car_number_pg_data:/var/lib/postgresql/data
    restart: on-failure
  
  redis:
    container_name: dev_bot_car_number_redis
    image: redis
    restart: on-failure

  bot:
    container_name: dev_bot_car_number
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: ../.env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    