MAIN = "main"
CANCEL = "cancel"

USER = "user_menu"
USER_ADD = "user_add"
USER_DEL = "user_delete"
USER_DEL_CONFIRM = "user_delete_confirm"

AUTO_MENU = "auto_menu"
AUTO_ADD = "auto_add"
AUTO_SAVE = "auto_save"
AUTO_DEL = "auto_delete"
AUTO_DEL_CONFIRM = "auto_delete_confirm"

SEARCH = "search"

BACK_TXT = "<< Назад"
DEL_CONFIRM_TXT = "Подтвердить Удаление"
USER_MENU_TXT = "Мои Данные"
AUTO_MENU_TXT = "Мои Автомобили"
SEARCH_TXT = "Поиск"
ADD_TXT = "Добавить"
DELETE_TXT = "Удалить"
SAVE_TXT = "Сохранить"
CANSEL_TXT = "Отмена"
SEND_TXT = "Отправить"
